import { LayoutData } from "@/types";
import Link from "next/link";
import styles from "@/styles/Home.module.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Head from "next/head";

export default function MainLayout({ children }: LayoutData) {
  return (
    <div>
      <Head>
        <title>Tech Shop</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div>
<header>
  {/* <!-- Navbar --> */}
  <nav className="navbar navbar-expand-lg navbar-dark" >
    <div className="container-fluid">
      {/* <!-- Navbar brand --> */}
      <a className="navbar-brand nav-link" target="_blank" href="https://nextjs.org/docs">
        <strong>NEXT.JS</strong>
      </a>
      <div className="navbar-expand" id="navbarExample01">
        <ul className="navbar-nav me-auto mb-2 mb-lg-0">
          <li className="nav-item active">
            <Link className="nav-link" aria-current="page" href="/">Home</Link>
          </li>
          <li className="nav-item">
            <Link className="nav-link" href="/about-us" rel="nofollow">About Us</Link>
          </li>
          <li className="nav-item">
            <Link className="nav-link" href="/shop" rel="nofollow">Shop</Link>
          </li>
          <li className="nav-item">
            <Link className="nav-link" href="/users">Users</Link>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {/* <!-- Navbar --> */}

  {/* <!-- Carousel wrapper --> */}
  <div id="introCarousel" className="carousel slide carousel-fade shadow-2-strong" data-mdb-ride="carousel">
  
    <div className="carousel-inner">
      {/* <!-- Single item --> */}
      <div className="carousel-item active">
        <div className="mask" >
          <div className="d-flex justify-content-center align-items-center h-100">
            <div className="text-white text-center">
              <h1 className="mb-3 pt-5">Learn Next.Js with Singidunum</h1>
              <h5 className="mb-4">Best & free guide of responsive web design</h5>
              <a className="btn btn-outline-light btn-lg m-2" href="https://fir.singidunum.ac.rs/"
                role="button" rel="nofollow" target="_blank">Start tutorial</a>
              <a className="btn btn-outline-light btn-lg m-2" href="https://mdbootstrap.com/docs/standard/"
                target="_blank" role="button">More About Us</a>
            </div>
          </div>
        </div>
      </div>

    </div>

    <a className="carousel-control-prev" href="#introCarousel" role="button" data-mdb-slide="prev">
      <span className="carousel-control-prev-icon" aria-hidden="true"></span>
      <span className="sr-only">Previous</span>
    </a>
    <a className="carousel-control-next" href="#introCarousel" role="button" data-mdb-slide="next">
      <span className="carousel-control-next-icon" aria-hidden="true"></span>
      <span className="sr-only">Next</span>
    </a>
  </div>
</header>
      </div>
      <div>{children}</div>
      <div>
        <footer className={styles.footer}>
          <p>@2023 Time to Code! - TechShop Next Js Project</p>
        </footer>
      </div>
    </div>
  );
}
